//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChallengeEntities : DbContext
    {
        public ChallengeEntities()
            : base("name=ChallengeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<SeriesTeamPlayer> SeriesTeamPlayers { get; set; }
        public virtual DbSet<SeriesTeam> SeriesTeams { get; set; }
        public virtual DbSet<SeriesType> SeriesTypes { get; set; }
        public virtual DbSet<BetDetail> BetDetails { get; set; }
        public virtual DbSet<BetType> BetTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Match_bets> Match_bets { get; set; }
        public virtual DbSet<MatchChallenge> MatchChallenges { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<MemberTransaction> MemberTransactions { get; set; }
        public virtual DbSet<MemberWallet> MemberWallets { get; set; }
        public virtual DbSet<MatchBet> MatchBets { get; set; }
    }
}
