//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchChallenge
    {
        public int Id { get; set; }
        public int MatchBetId { get; set; }
        public int MemberId { get; set; }
        public int Amount { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiledDate { get; set; }
    
        public virtual Match_bets Match_bets { get; set; }
        public virtual Member Member { get; set; }
        public virtual MatchBet MatchBet { get; set; }
    }
}
