//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nationality
    {
        public int id { get; set; }
        public string Nation { get; set; }
        public string Code { get; set; }
        public string Logo { get; set; }
        public byte IsActive { get; set; }
    }
}
