//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Match_bets = new HashSet<Match_bets>();
            this.SeriesTeamPlayers = new HashSet<SeriesTeamPlayer>();
            this.MatchBets = new HashSet<MatchBet>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public int Nationality { get; set; }
        public string Bats { get; set; }
        public string Bowls { get; set; }
        public Nullable<decimal> Credits { get; set; }
        public string Logo { get; set; }
        public Nullable<decimal> TotalPoints { get; set; }
        public byte IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match_bets> Match_bets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeriesTeamPlayer> SeriesTeamPlayers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchBet> MatchBets { get; set; }
    }
}
